"""Criando tabela de locacoes

Revision ID: e44d9ccd44c7
Revises: d7e1c8a4b2f0
Create Date: 2026-09-02 13:32:22.448878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44d9ccd44c7'
down_revision = 'd7e1c8a4b2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('filme_id', sa.Integer(), nullable=False),
    sa.Column('data_locacao', sa.DateTime(), nullable=True),
    sa.Column('data_devolucao_prevista', sa.DateTime(), nullable=True),
    sa.Column('data_devolucao', sa.DateTime(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locacoes')
    # ### end Alembic commands ###
