"""Alterando status da locacao

Revision ID: fa165276cc19
Revises: e44d9ccd44c7
Create Date: 2026-09-02 13:54:24.375000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa165276cc19'
down_revision = 'e44d9ccd44c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locacoes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locacoes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)

    # ### end Alembic commands ###
